# Generated by Django 3.2.4 on 2026-01-08 07:24

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import helios.datatypes
import helios.models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_election_cast_consent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='applications_ends_at',
            field=models.DateTimeField(default=helios.models._default_applications_ends_at, help_text='When applications stop to be accepted', null=True, verbose_name='Applications stops at'),
        ),
        migrations.AddField(
            model_name='election',
            name='applications_starts_at',
            field=models.DateTimeField(default=helios.models._default_applications_starts_at, help_text='When applications start to be accepted', null=True, verbose_name='Applications starts at'),
        ),
        migrations.AlterField(
            model_name='castvote',
            name='previous',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='election',
            name='cancelation_reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='election',
            name='cast_consent_text',
            field=models.TextField(blank=True, default=None, help_text='Require voters to accept specified terms in order to cast a vote.', null=True, verbose_name='Cast consent test'),
        ),
        migrations.AlterField(
            model_name='election',
            name='communication_language',
            field=models.CharField(max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='election',
            name='compute_results_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_module',
            field=models.CharField(choices=[('simple', 'Simple election with one or more questions'), ('parties', 'Party lists election'), ('score', 'Score voting election'), ('stv', 'Single transferable vote election'), ('sav', 'Satisfaction Approval Voting'), ('unigovgr', 'Greek Universities single governing bodies election')], default='simple', help_text='Choose the type of the election', max_length=250, verbose_name='Election type'),
        ),
        migrations.AlterField(
            model_name='mixpart',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='compute_results_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='decrypt_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='link_id',
            field=models.CharField(default='', max_length=255, verbose_name='Poll link group'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='linked_ref',
            field=models.CharField(default='', max_length=255, verbose_name='Poll reference id'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='mix_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='partial_decrypt_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='validate_create_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='validate_mixing_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='validate_voting_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='zeus_partial_decrypt_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='pollmix',
            name='mix_file',
            field=models.FileField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/user/zeus/settings/../data/mixes'), upload_to=helios.models.dummy_upload_to),
        ),
        migrations.AlterField(
            model_name='pollmix',
            name='mix_type',
            field=models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], default='local', max_length=255),
        ),
        migrations.AlterField(
            model_name='pollmix',
            name='name',
            field=models.CharField(default='Zeus mixnet', max_length=255),
        ),
        migrations.AlterField(
            model_name='pollmix',
            name='remote_protocol',
            field=models.CharField(choices=[('helios', 'Helios'), ('verificatum', 'Verificatum'), ('zeus_client', 'Zeus server')], default='zeus_client', max_length=255),
        ),
        migrations.AlterField(
            model_name='pollmix',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('mixing', 'Mixing'), ('validating', 'Validating'), ('error', 'Error'), ('finished', 'Finished')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='voter',
            name='exclude_reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voterfile',
            name='voter_file',
            field=models.FileField(max_length=250, null=True, upload_to='voters/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('group', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=255)),
                ('presentation', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='helios.election')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, helios.datatypes.LDObjectContainer),
        ),
    ]
