# Generated by Django 3.2.4 on 2026-01-08 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0006_auto_20260108_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='group',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='uuid',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('election', 'email')},
        ),
    ]
