# Generated by Django 3.2.4 on 2026-01-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0007_auto_20260108_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='surname',
            field=models.CharField(max_length=255),
        ),
    ]
