# Generated by Django 3.2.4 on 2026-01-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0008_auto_20260108_1026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
