# Generated by Django 3.2.4 on 2026-01-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0010_auto_20260109_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1, help_text='Number of seats to be filled by this election', verbose_name='Number of seats'),
        ),
    ]
