# Generated by Django 3.2.4 on 2026-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0011_election_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('election', 'email')},
        ),
    ]
