# Generated by Django 3.2.4 on 2026-01-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heliosauth', '0004_sms_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsbackenddata',
            name='sender',
            field=models.CharField(default='ZEUS', max_length=255),
        ),
    ]
